//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int codbit { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public string terminal { get; set; }
        public string usuario { get; set; }
        public string aplicacion { get; set; }
    }
}
