//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diploma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diploma()
        {
            this.Legalizacion = new HashSet<Legalizacion>();
            this.ListadeEstudiantes = new HashSet<ListadeEstudiantes>();
        }
    
        public int idDiploma { get; set; }
        public System.DateTime fecha { get; set; }
        public string metadatos { get; set; }
        public string codigohex { get; set; }
        public string codigoLegalizacion { get; set; }
        public int idListaEstudiante { get; set; }
        public int idGrupoDiploma { get; set; }
    
        public virtual GrupoDiploma GrupoDiploma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Legalizacion> Legalizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListadeEstudiantes> ListadeEstudiantes { get; set; }
    }
}
