//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public int nroRegistroEst { get; set; }
        public string loginEstudiante { get; set; }
        public string passEstudiante { get; set; }
        public string correo { get; set; }
        public int CI { get; set; }
        public int idListaEstudiante { get; set; }
        public int idRol { get; set; }
    
        public virtual ListadeEstudiantes ListadeEstudiantes { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
