//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadeEstudiantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListadeEstudiantes()
        {
            this.Estudiante = new HashSet<Estudiante>();
        }
    
        public int idListaEstudiante { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string correo { get; set; }
        public string paralelo { get; set; }
        public double promedio { get; set; }
        public int idGrupoDiploma { get; set; }
        public int idGestion { get; set; }
        public Nullable<int> idDiploma { get; set; }
    
        public virtual Diploma Diploma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estudiante> Estudiante { get; set; }
        public virtual Gestion Gestion { get; set; }
        public virtual GrupoDiploma GrupoDiploma { get; set; }
    }
}
