//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalColegio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalColegio()
        {
            this.GrupoDiploma = new HashSet<GrupoDiploma>();
            this.Rol = new HashSet<Rol>();
        }
    
        public int nroRegistroPColegio { get; set; }
        public string loginPColegio { get; set; }
        public string passPColegio { get; set; }
        public string correo { get; set; }
        public int CI { get; set; }
        public int idColegio { get; set; }
    
        public virtual Colegio Colegio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoDiploma> GrupoDiploma { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
