//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_NoPerfil
    {
        public Nullable<int> id { get; set; }
        public string nombreCompleto { get; set; }
        public Nullable<int> telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<int> CI { get; set; }
        public string paralelo { get; set; }
        public Nullable<double> promedio { get; set; }
        public string nombrePromo { get; set; }
        public int año { get; set; }
        public string colegio { get; set; }
    }
}
