//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Perfil
    {
        public string nombreCompleto { get; set; }
        public int telefono { get; set; }
        public string direccion { get; set; }
        public int CI { get; set; }
        public string paralelo { get; set; }
        public double promedio { get; set; }
        public string nombrePromo { get; set; }
        public int año { get; set; }
        public System.DateTime fecha { get; set; }
        public string colegio { get; set; }
        public string metadatos { get; set; }
        public string codigohex { get; set; }
        public string codigoLegalizacion { get; set; }
        public int id { get; set; }
    }
}
