//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinisteriodeEducacionMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VR5
    {
        public string NombreCompleto { get; set; }
        public string nombrePromo { get; set; }
        public string NombreColegio { get; set; }
        public int Año { get; set; }
        public double promedio { get; set; }
    }
}
